name: Artifact Example

on: 
  push:
    paths:
      - 'actions_trial/workflows/1.yaml' 

jobs:
  generate-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script and create output
      run: |
        echo "This is an example output" > output.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: example-artifact
        path: output.txt

  use-artifact:
    runs-on: ubuntu-latest
    needs: generate-artifact

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: example-artifact
        path: ./downloaded

    - name: Show artifact content
      run: |
        cat ./downloaded/output.txt
